name: Publish Package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" # Matches the 'v{{version}}' pattern

# Optional: Specify the environment if you configured one on
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for OIDC authentication
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1 # Sets up the Dart/Flutter SDK
      - name: Install dependencies
        run: dart pub get
      - name: Publish package
        run: dart pub publish --force # --force skips the manual confirmation prompt
